### PR TITLE
maxime: added cohort-id on project (based upon refactor-populate branch)

### PR DESCRIPTION
**Pull request by sidohaakma**

### CODE REVIEW

**Comment by sidohaakma** [comment]
@tenroc: I have rebased your PR on the latest version of the master. Can you check if the amendments you made are still correct?

I have relocated the create project function to helpers and made it more agnostic. The actual cohort-id is still amended in the populateCore and populateOutcome but directly in the projectname which is used in other functions as well.

**Comment by tenroc** [comment]
It looks good to me!
However, there's something I don' get:
project is defined in the lifecycle.project.create call in lc.populate.core and lc.populate.outcomes, but is overwritten anyway by the lc.project.create call by the function arguments. Isn't that redundant?

**Comment by sidohaakma** [comment]
Ah I see, yes you are right. Where would you construct the projectname then? In the lc.populate.core and outcome or in the lc.create.project call?

**Comment by tenroc** [comment]
as we re-use the project variable outside ou lc.project.create and as lc.project.create isn't intended to be used as a standalone version, I would drop the project definition from lc.project.create. I made the commit but feel free to reverse it if you don't think that it's a good solution.
Also, the dict_kind and dict_version arguments are now only used in the messages. If they're not considered that useful, we can further simplify function calls.

**Comment by sidohaakma** [comment]
@tenroc Yes, I agree let's strip it further. We can only display a message of which project is created instead of the way it is done now. I will amend it a bit more then.

**Comment by sidohaakma** [comment]
@tenroc I have amending it a bit, but I still need the dict_kind and dict_version for the project description. Or we could send the description in the signature instead of composing it in the function. I would like some kind of description within Opal to make clear what data dictionary you are looking at.

**Comment by sidohaakma** [comment]
@tenroc I am going to close the other PR, so we can proceed with this one. Is that ok with you?

**Comment by tenroc** [comment]
@ Sure! you can close the PR.
I probably missed it, but I can't see how dict_kind and dict_version are still used in the current lc.project.create function?

Anyway, currently, the project 'variable' composition is strictly deterministic, and therefore we can easily infere its composition and extract dict kind and dict version from it like so:

````
a <- strsplit(project, "_")

dict_kind <- a[[1]][3]

dict_version <- paste(a[[1]][4], "_", a[[1]][5], sep ="")
````

However it has a bad failure mode if we ever decide to let the user freely define the project name. So if we do need the arguments, the best course is probably to leave them in.

**Comment by sidohaakma** [comment]
@tenroc It is used in the post to the api of Opal to construct the description of the project. 

Check:

line 46:

```
json <- sprintf('{"database":"%s","description":"%s","name":"%s","title":"%s"}', database_name, paste('Project for [ ', dict_kind ,' ] variables and data dictionary version: [ ', dict_version,' ]', sep = ''), project, project)
```

Maybe split it indeed? I do not think we are ever going to have less information in the project name.

**Comment by tenroc** [comment]
@sidohaakma oh yes, I did miss that. Either will work. I can make a pull request if you prefer to drop the arguments. Otherway it works as intended as it is.

**Comment by sidohaakma** [comment]
@tenroc I am going to merge this in the afternoon. Then iterate over the new state. I am going to rebase the refactor-reshape PR as well, after this merge. Then it will be mergeable again at least. 

- So after the merge of this PR create a new PR with dropping the variables
- Merge the reshape-refactor with master and fix bugs after testing
- Create one call to bootstrap the tables in Opal and upload the data

Maybe have another call with Angela what she prefers, regarding defining the number of variabels. I think that it is important to not have new variables created in the reshape function. Which are not in the harmonisation manual. That means that we somehow need to know how many and with what interval are defined in the harmonisation manuals. We could try to automate this in the new proposal you have written.

**Comment by tenroc** [comment]
Yes, we should ask Angela how to handle the definition of repeated variables. What I don't know is how datashield reacts to missing variables in the repeated measures tables. Or  the rationale behind the need to create empty variables? 
Because wouldn't it be much simpler to just handle the process post-upload at the datashield level? like so: if a variables exist in one of the cohort but not the other, just create an empty variable for the other cohorts in the R environment. That would also allow us to not rely too heavily on hard-defined age limits for the repeated variables.

For the upload process, I gave it some thoughts: 

We could just write a lc.upload function that would download the dictionaries, then successively run lc.populate and lc.reshape (maybe with an argument to allow to run just one or the other?) and then delete the dictionaries.

**Comment by sidohaakma** [comment]
@tenroc For the first part, we do not need to create empty variables. however you could generate more variables if you do not specify the range. So for instance height_600 if they have that in specified in the source data. You want to be able to filter those out. Missing you do not have to deal with I think.

The second part. Yes an overall upload function would be very nice. In terms of order, first the reshape and then the upload or the other way around.

**Pull request merged**
