### PR TITLE
Refactor reshape

### PR DESCRIPTION
**Pull request by sidohaakma**

### CODE REVIEW

**Comment by sidohaakma** [comment]
@tenroc NICE! Can we work on this further? So we can drop the variablesOutcome as well?

**Comment by tenroc** [comment]
@sidohaakma It's already the case: the reshape function infers which dictionnary to use from dict_kind :)
However if we plan to use this we need to come up with a solution for the number of repeated variables to reshape -- that is, if the goal is to have the exact same number of variables, empty or not, in all the databases. The current method creates just the necessary number for the cohort that is being reshaped --. However the current solution is just to hardcode it in the 'variable' files so it's not ideal anyway.

**Comment by tenroc** [comment]
@sidohaakma I resolved the merge conflicts with the master branch. It should be in a working state, even if as discussed, more work (and testing) is needed. We can work off this branch to get it to a point where you feel confortable to merge it, otherwise, You can go ahead, review and merge, and we will work directly on the master branch.

**Comment by sidohaakma** [comment]
@tenroc Check: https://github.com/lifecycle-project/analysis-protocols/pull/28. This is the same as yours only on the remote. Let's work on this. We need to create the lc.upload.core and lc.upload.outcome I think to use the data dictionaries in the reshape function. We need to extract the download of these files out of the populate functions and do them earlier.

In the reshape we have still differences regarding the tables in the core-vars we have the trimester table added (next to the non, yearly and monthly repeated measures).

Maybe add the existing 2 functions:

lc.reshape.core and .outcome and reuse the non, yearly and monthly then add for the core-vars the trimester table and for the outcome the weekly table.

What do you think?

Kind regards,

Sido

**Pull request closed without merging**
