### PR TITLE
refactor: refactor reshape.core and reshape.outcome

### PR DESCRIPTION
**Pull request by sidohaakma**
- create lc.upload
- refactor populate.core and populate.outcome (we need the data dictionaries for both populating and reshaping)

### CODE REVIEW

**Comment by sidohaakma** [comment]
@tenroc 

Hi Maxime,

We need to create the lc.upload.core and lc.upload.outcome I think to use the data dictionaries in the reshape function. We need to extract the download of these files out of the populate functions and do them earlier.

In the reshape we have still differences regarding the tables in the core-vars we have the trimester table added (next to the non, yearly and monthly repeated measures).

Maybe add the existing 2 functions:

lc.reshape.core and .outcome and reuse the non, yearly and monthly then add for the core-vars the trimester table and for the outcome the weekly table.

What do you think?

Kind regards,

Sido

**Comment by tenroc** [comment]
@sidohaakma 
Hi Sido, 

I created lc.upload as a wrapper around lc.dict.download, lc.populate and lc.reshape. I also modified the reshape functions and the populate function to account for weekly repeated variables. Plus I made the populate function agnostic, eliminating the need to distinguish between core and outcome.
For now, the weekly function are checked against dict_kind, which is not ideal but as we discussed in Bristol, a better solution would require looking into the github API. 
Also, for now, I kept the old system: two distinct projects are created, one for "core" and one for "outcome". As such, the lc.upload function need to be run twice, once for both types. 
I'll investigate how to make a better solution when I have a little bit more time. Maybe specify the types of dictionary that you want to operate on in a single vector?
I couldn't test the package as the molgenis test server gives me a 402 error when I try to log in, and we really should test it, but at least it builds without issues.

Kind regards,

Maxime

**Comment by tenroc** [comment]
Oh, I also noticed you needed something done for the trimester repeated variables.
I think the best way to add differential handle for the core and outcome dictionnaries is to keep checking for dict_kind rather than write two different reshape and populate function. It keeps code duplication lower?
At least until we can integrate the github API or find another way to check which data needs to be handled... Maybe by catching curl errors?.
What do you think?

**Comment by tenroc** [comment]
@sidohaakma Hi Sido, and Happy new year!

I noticed the Molgenis test server went back online, so I could test the package and debug it. It should be in a working state as of the latest commit, at least for the core variables (I couldn't test against the outcome ones as I don't have a test database for those).

Three things:

- Do you have some code for the reshaping of the trimester variables? I can write the function but if you already have there's no point in doing so.

- I The package would be a lot less constrained if we could drop the check against dict_kind for the dictionary download and the reshaping. That would presume something like that: 
Check if the dictionnary url exist --> Infer which actions need to be taken from there. Do you have an idea dor an implementation? Rcurl does that but I'm trying to avoid pulling in more dependencies.

- Right now, it doesn't fail very gracefully. Could we try to come up with a plan for how we want it to fail? Currently, if one operation fails it takes down the entire process.

Thanks!

Kind regards,

Maxime

**Comment by tenroc** [comment]
@sidohaakma Hi Sido!
I integrated the quaterly variables in the reshape and populate functions, and resolved the merge conflicts with master, so the branch should be up to date and in a working state.
However, travis throws some errors for the windows build and I can't make sense of them, if you want to take a look?

Also, I'm quite sure that we could achieve a significant reduction of the reshape script and remove quite a lot of code duplication by making the reshape function agnostic (the type of data to be reshaped should really be an argument rather than a separate function). I'll look into it, but as of now this branch should be working, even if it needs thorough testing.

**Comment by sidohaakma** [comment]
@tenroc 

Hi Maxime,

I have fixed the populate function. I need to call the github api to look which files are in the directories and download them that way. That is an enhancement I want to put in another pullrequest after this one.

I am now fixing the generate yearly repeated measures as a generic method. That is kind of hard. Could you take a look at it as well? I am using the WP5 data to test. I am stuck in the gather method.

Thanks so much for all the work so far.

Kind regards,

Sido

**Comment by tenroc** [comment]
@sidohaakma 
Hi Sido, 
Regarding the github API, I thinks that would be a great improvement! 
For the yearly repeated measures: It's broken? What's the error it's giving you?
Kind regards,

Maxime

**Comment by sidohaakma** [comment]
@tenroc: We are nearing the end of the refactoring. I am testing the code with Angela tomorrow. I think in the future we can make the reshape function more generic as well.

**Comment by tenroc** [comment]
@sidohaakma Nice! I was actually just looking at how to do that. Let me know how the test goes. Oh and if you chose to use maditr or data.table we can drop dependency to tidyr? But we can look at the dependencies while making the reshape function generic

**Comment by sidohaakma** [comment]
@tenroc Yes, that would be nice. I have little oversight of which packages can do what in terms of functionality. I think we can use tidyr instead of maditr and use spread? Or something like that. I think we can make the reshape more generic using one function to do the repeated measures depending what you specify (yearly, monthly, etc..).

**Comment by sidohaakma** [comment]
@tenroc I am going to merge these changes into the master. The test with Angela was successful.  A few minor amendments and then it is ok.

**Pull request merged**
